LF EDGE Renaming
fido-device-onboard/epid-verification-service pull request #48
Opened 2023-05-09 03:29 UTC by tPeeush

2023-05-09 08:14 UTC, DukeDavis12 approved these changes

2023-05-09 08:20 UTC, DukeDavis12 commented on build/build.sh
>  REMOTE_BRANCH=master
Update the BASE URL in https://github.com/secure-device-onboard/epid-verification-service/blob/master/download-cryptomaterials.sh#L12

to `BASE_URL="http://verifier.fdorv.com"`

2023-05-09 08:20 UTC, DukeDavis12 requested changes
Update the base URL.

2023-05-11 09:10 UTC, DukeDavis12 approved these changes

2023-05-11 09:14 UTC, KiranSukhavasi approved these changes

2023-05-11 09:14 UTC, v-vasavi approved these changes

2023-05-11 10:19 UTC, merged